dc_gov_haven_role:
    resource: "@DCGovHavenBundle/Resources/config/routing/role.yml"
    prefix:   /role

login:
    path: /admin/login
    defaults: { _controller: "DCGovHavenBundle:Security:login" }
    
login_check:
    path: /admin/login_check

logout:
    path: /logout
    
dc_gov_haven_homepage:
    path:      /
    defaults:  { _controller: "DCGovHavenBundle:Default:index" }

dc_gov_haven_identry:
    resource: "@DCGovHavenBundle/Resources/config/routing/identry.yml"
    prefix:   /identry