login:
    path: /login
    defaults: { _controller: "DCGovHavenBundle:Security:login" }
    
login_check:
    path: /login_check

logout:
    path: /logout

dc_gov_haven_login:
    path:      /
    defaults:  { _controller: "DCGovHavenBundle:Security:login" }    

dc_gov_haven_homepage:
    path:     /safehaven/
    defaults: { _controller: "DCGovHavenBundle:Default:index" }