dc_gov_haven_home:
    path:      /
    defaults:  { _controller: "DCGovHavenBundle:Default:index" }

dc_gov_haven_role:
    resource: "@DCGovHavenBundle/Resources/config/routing/role.yml"
    prefix:   /role

dc_gov_haven_login:
    resource: "@DCGovHavenBundle/Resources/config/routing/login.yml"
    prefix:   /login

dc_gov_haven_admin:
    resource: "@DCGovHavenBundle/Resources/config/routing/admin.yml"
    prefix:   /admin

dc_gov_haven_identry:
    resource: "@DCGovHavenBundle/Resources/config/routing/identry.yml"
    prefix:   /identry

dc_gov_haven_report:
        resource: "@DCGovHavenBundle/Resources/config/routing/report.yml"
        prefix:   /report    