services:
#    dc_gov_haven.example:
#        class: DCGov\HavenBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
     app.email:
        class:  DCGov\HavenBundle\Service\Email
        arguments: [ "@service_container" ]
        kernel.event_listener:
            event: kernel.controller