imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# assetic for asset management
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    assets:
        glyphicons-halflings-regular-woff:
            inputs:
                 - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.woff"
            output: fonts/glyphicons-halflings-regular.woff
        glyphicons-halflings-regular-woff2:
            inputs: 
                 - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2"
            output: fonts/glyphicons-halflings-regular.woff2
        
        fontawesome-webfont-ttf:
            inputs: 
                 - "%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.ttf"
            output: fonts/fontawesome-webfont.tiff
        
        fontawesome-webfont-woff:
            inputs: 
                 - "%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.woff"
            output: fonts/fontawesome-webfont.woff

        fontawesome-webfont-woff2:
            inputs: 
                 - "%kernel.root_dir%/../vendor/components/font-awesome/fonts/fontawesome-webfont.woff2"
            output: fonts/fontawesome-webfont.woff2
                    
        jquery_js:
            inputs: 
                 - "%kernel.root_dir%/../vendor/components/jquery/jquery.min.js"
            output: js/jquery.js
        
        jquery_datatable_js:
            inputs: 
                 - "%kernel.root_dir%/../vendor/datatables/datatables/media/js/jquery.dataTables.min.js"
                 - "%kernel.root_dir%/../vendor/datatables/datatables/media/js/dataTables.bootstrap.min.js"
            output: js/datatables.js
            
        jquery_datatable_css:
            inputs:
                - "%kernel.root_dir%/../vendor/datatables/datatables/media/css/dataTables.bootstrap.min.css"
            filters:
                - cssrewrite
            output: css/datatable.css
        
        jquery_datatable_image_sort_asc:
            inputs: 
                - "%kernel.root_dir%/../vendor/datatables/datatables/media/images/sort_asc.png"
            output: images/sort_asc.png

        jquery_datatable_image_sort_desc:
            inputs: 
                - "%kernel.root_dir%/../vendor/datatables/datatables/media/images/sort_desc.png"
            output: images/sort_desc.png
        
        jquery_datatable_image_sort_both:
            inputs: 
                - "%kernel.root_dir%/../vendor/datatables/datatables/media/images/sort_both.png"
            output: images/sort_both.png
                                
        bootstrap_css:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.min.css"
                - "%kernel.root_dir%/../vendor/bootstrap-select/bootstrap-select/dist/css/bootstrap-select.css"
            filters:
                - cssrewrite
            output: css/bootstrap.css

        fontawesome_css:
            inputs:
                - "%kernel.root_dir%/../vendor/components/font-awesome/css/font-awesome.css"
            filters:
                - cssrewrite
            output: css/font-awesome.css
                
        bootstrap_js:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.min.js"
         #      - %kernel.root_dir%/../vendor/twbs/bootstrap/js/bootstrap-transition.js
         #      - %kernel.root_dir%/../vendor/twbs/bootstrap/js/bootstrap-alert.js
         #       - %kernel.root_dir%/../vendor/twbs/bootstrap/js/bootstrap-button.js
         #       - %kernel.root_dir%/../vendor/twbs/bootstrap/js/bootstrap-carousel.js
         #       - %kernel.root_dir%/../vendor/twbs/bootstrap/js/bootstrap-collapse.js
         #       - %kernel.root_dir%/../vendor/twbs/bootstrap/js/bootstrap-dropdown.js
         #       - %kernel.root_dir%/../vendor/twbs/bootstrap/js/bootstrap-modal.js
         #       - %kernel.root_dir%/../vendor/twbs/bootstrap/js/bootstrap-tooltip.js
         #       - %kernel.root_dir%/../vendor/twbs/bootstrap/js/bootstrap-popover.js
         #       - %kernel.root_dir%/../vendor/twbs/bootstrap/js/bootstrap-scrollspy.js
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js"
         #       - %kernel.root_dir%/../vendor/twbs/bootstrap/js/bootstrap-typeahead.js
         #       - %kernel.root_dir%/../vendor/twbs/bootstrap/js/bootstrap-affix.js
                - "%kernel.root_dir%/../vendor/bootstrap-select/bootstrap-select/dist/js/bootstrap-select.js"
            output: js/bootstrap.js    
    
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#Light SAML Bridge
light_saml_symfony_bridge:
    own:
        entity_id: http://dev.haven.com/app_dev.php/saml/metadata.xml
        credentials:
            -
                certificate: "%kernel.root_dir%/../src/DCGov/HavenBundle/Resources/config/saml/cert/saml.crt"
                key:         "%kernel.root_dir%/../src/DCGov/HavenBundle/Resources/config/saml/cert/saml.key"
                password:    ~
    party:
        idp:
            files:
                - "%kernel.root_dir%/../vendor/lightsaml/lightsaml/web/sp/openidp.feide.no.xml"
#               - "%kernel.root_dir%/../vendor/lightsaml/lightsaml/web/sp/testshib-providers.xml"
                - "%kernel.root_dir%/../src/DCGov/HavenBundle/Resources/config/saml/idp/salesforce.samlidp.xml"
                - "%kernel.root_dir%/../src/DCGov/HavenBundle/Resources/config/saml/idp/idp.haven.xml"
    store:
        id_state: id_store

light_saml_sp:
    username_mapper:
        # default fallback list of attributes for
        # lightsaml_sp.username_mapper.simple service to use to
        # resolve SAML Response to username
        - "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
        - "http://schemas.xmlsoap.org/claims/EmailAddress"
        - "http://schemas.xmlsoap.org/claims/CommonName"
        - "http://schemas.microsoft.com/ws/2008/06/identity/claims/windowsaccountname"
        - "urn:oid:0.9.2342.19200300.100.1.3"
        - "uid"
        - "urn:oid:1.3.6.1.4.1.5923.1.1.1.6"
        - "@name_id@"
