# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
   id_store:
      class: DCGov\HavenBundle\Store\IdStore
      arguments:
          - "@=service('doctrine').getManager()"
          - "@lightsaml.system.time_provider"
   user_creator:
        class: DCGov\HavenBundle\Security\User\UserCreator
        arguments:
            - "@=service('doctrine').getManager()"
            - "@lightsaml_sp.username_mapper.simple"
        
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

   app.twig_extension:
        class: DCGov\HavenBundle\Twig\DCGovTwigExtension
        public: false
        tags:
            - { name: twig.extension }