identry_index:
    path:     /
    defaults: { _controller: "DCGovHavenBundle:IdEntry:index" }
    methods:  GET

identry_show:
    path:     /{id}/show
    defaults: { _controller: "DCGovHavenBundle:IdEntry:show" }
    methods:  GET

identry_new:
    path:     /new
    defaults: { _controller: "DCGovHavenBundle:IdEntry:new" }
    methods:  [GET, POST]

identry_edit:
    path:     /{id}/edit
    defaults: { _controller: "DCGovHavenBundle:IdEntry:edit" }
    methods:  [GET, POST]

identry_delete:
    path:     /{id}/delete
    defaults: { _controller: "DCGovHavenBundle:IdEntry:delete" }
    methods:  DELETE
