dev_person_index:
    path:     /
    defaults: { _controller: "DCGovHavenBundle:Person:index" }
    methods:  GET

dev_person_show:
    path:     /{id}/show
    defaults: { _controller: "DCGovHavenBundle:Person:show" }
    methods:  GET



